# Site settings
title: "Syarmine Shah"
description: "A Github Page for my resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Syarmine Shah"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "syarmineshah@yahoo.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Kuala Lumpur, Malaysia"

resume_header_contact_info:     "Hi👋! I'm Syarmine Shah, welcome to my website."
display_header_contact_info:    "true"

resume_header_intro: "<p> 
                          <li> I am a policy analyst, data analyst and health economist with over 5 years of professional experience. I hold three Microsoft certifications and an AWS certification.</li>
                          <br>
                          <li> Previously, I served in the public insurance sector at Malaysia's Social Security Organisation. I was responsible of being part of national taskforce for COVID-19 financing and policy interventions. My role involved leveraging tools such as Excel, Microsoft PowerBI, and the Power Platform suite (PowerApps, PowerAutomate, and Power Virtual Agents) to develop a dataflow that significantly aided in monitoring and reporting.</li>                         
                          <br>
                          <li> I then pursue my recent master’s degree, specialising in policy analysis with focus on health economics - pertaining allocation, cost-effectiveness, evaluation and effective use of resources. I extensively used the R programming language for statistical and regression analysis and integrated my coursework with Tableau and RShiny to present my findings. In the process, I explored the use cases of artificial intelligence and machine learning in financing development and policy decisions on a global scale as part of my thesis, where I discover the need of secure, scalable, and cost-effective solutions through cloud computing technology.</li>
                          <br>
                          <li> With that being said, I am currently expanding my skill set by learning cloud solutions, specifically Azure and AWS, while dabbling with Python for its wide-ranging applications in machine learning that are prevalent in the industry.</li>
                          <br>
                          <li> As the world is moving towards generative AI and predictive analytics, it has led me to transition into data-driven journey especially in data analysis and data scientist role leveraging data ecosystem with scalalable cloud solutions.</li></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Syarmine"
  resume_twitter_url:           "http://twitter.com/SyarmineS"
  resume_dribbble_url:          false
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/drsyarmine-shah/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           false
  resume_medium_url:            false
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
