# Site settings
title: "Syarmine Shah"
description: "A Github Page for my resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Syarmine Shah"
resume_title:                   "Briefly About Myself"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "syarmineshah@yahoo.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Kuala Lumpur, Malaysia"

resume_header_contact_info:     "Kuala Lumpur • syarmineshah@yahoo.com"
display_header_contact_info:    "false"

resume_header_intro: "<p> <li> I am Syarmine Shah, an analyst with and certified Microsoft x3 and certified AWS x1.</li><br>
                          <li> My previous roles as an analyst and medical doctor have equipped me with proficiency in Excel, Microsoft PowerBI, SQL, and the Power Platform suite (including PowerApps, PowerAutomate, and Power Virtual Agents). </li><br>                         <li>During my master’s degree, I specialized in policy (health economics) utilising R programming language for statistical and regression analysis. <br>
                          <li> Currently, I am expanding my skill set to include cloud solutions, specifically Azure and AWS.</li><br>
                          <li> As the world moving towards AI and machine learning, it has led me to dabble with Python and the more scalalable cloud ecosystem </li></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Syarmine"
  resume_twitter_url:           "http://twitter.com/SyarmineS"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
